<?php

function wisski_navigator_menu() {

  $items = array();
  
  //  The settings for the wisski module in the admin page - might be useful later
  $items['navigate'] = array(
    'title' => 'Browse content',
    'description' => 'This is the WissKI-Template Navigator.',
    'page callback' => 'wisski_navigator_overview',
    'access arguments' => array('wisski access templateView'),
    'type' => MENU_NORMAL_ITEM, 
  );
  
  $items['navigate/%'] = array(
    'description' => 'This is the WissKI-Template Navigator.',
    'page callback' => 'wisski_navigator_overview_group',
    'page arguments' => array(1),
    'access arguments' => array('wisski access templateView'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['goto_navigate'] = array(
    'title' => 'Navigate',
    'page callback' => 'drupal_goto',
    'page arguments' => array('navigate'),
    'access arguments' => array('wisski access templateView'),
    'menu_name' => 'secondary-links',
    'weight' => -49,
  );  

  wisski_navigator_add_groups();

  return $items;
  
}

function wisski_navigator_form_alter(&$form, &$form_state, $form_id) {
    
  if($form_id == 'wisski_visualSettings') {
    $buttons = $form['buttons'];
    unset($form['buttons']);
    $form[] = (wisski_navigator_visualSettings());  
    $form['buttons'] = $buttons;
  }
}

/**
 * Make visual settings available
 *
 * @author Mark Fichtner
 *
 */
function wisski_navigator_visualSettings() {
  
  $form = array ();

  $form['wisski_navigator_fieldset'] = array(
    '#type' => 'fieldset',
    '#title' => t('Navigate Settings'),
    '#weight' => -10,
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );

  $form['wisski_navigator_fieldset']['wisski_navigator_resultItemsPerPage'] = array (
    '#type' => 'textfield',
    '#title' => t('Number of results'),
    '#description' => t('The Number of results to show in navigate per page. 0 can be set to show all at once. Be careful, this setting is very slow!'),
    '#default_value' => variable_get('wisski_navigator_resultItemsPerPage', 20),
    '#size' => 4,
    '#maxlength' => 255,
  );

  $form['wisski_navigator_fieldset']['wisski_navigator_styleResultPage'] = array(
    '#type' => 'radios',
    '#title' => t('Display Mode'),
    '#description' => t('Should navigate show as a list or as tiles?'),
    '#options' => array('list' => 'list', 'tiles' => 'tiles'),
    '#default_value' => variable_get('wisski_navigator_styleResultPage', 'list'),
  );
  
  $form['wisski_navigator_fieldset']['wisski_navigator_imageSupport'] = array(
    '#type' => 'checkbox',
    '#title' => t('Image Preview'),
    '#description' => t('Enable a small preview image in the navigate menu?'),
    '#return_value' => 'yes',
    '#default_value' => variable_get('wisski_navigator_imageSupport', 'yes'),
  );

  return $form;

}

function wisski_navigator_overview_group($groupid) {

  global $pager_page_array, $pager_total, $pager_total_items;
  
  include_once(drupal_get_path('module', 'wisski_pathbuilder') . '/wisski_pathbuilder.inc');
  $groups = wisski_pathbuilder_getGroups();

  if(in_array($groupid, $groups)) {
    $data = wisski_pathbuilder_getPathData($groupid);
    if($data['enabled'])
      $groupdata = $data;
  } else {
    return;
  }
  
  $page = isset($_GET['page']) ? $_GET['page'] : 0;
  
  $pager_page_array = explode(',', $page);
  
  $element = 0;
  $limit = variable_get('wisski_navigator_resultItemsPerPage', 30);
  
  $samepart = _wisski_pathbuilder_calculate_group_samepart($groupdata['id']);

  global $user;
  $vars = variable_get("wisski_pathbuilder_templateids", array());

  if(!isset($vars[$user->uid][$samepart["x" . (floor(count($samepart)/2))]]) ||
    $vars[$user->uid][$samepart["x" . (floor(count($samepart)/2))]] != $groupdata['id']) {
    $vars[$user->uid][$samepart["x" . (floor(count($samepart)/2))]] = $groupdata['id'];
    variable_set("wisski_pathbuilder_templateids", $vars);
  }

  /* We should not skip this, although the name generation got more intelligent */
  //preg_match_all('/![0-9]*/',$groupdata['short_name'], $matches);
  // Only take names which are not surrounded by brackets - brackets make them optional
  preg_match_all('/![0-9]*/',$groupdata['short_name'], $matches);

  preg_match_all('/(\{.*?)(![0-9]*)(.*?\})/',$data['short_name'], $optional_matches);
  
  // if a match is an optional match, kill it!
  foreach($matches[0] as $key => $match) {
    if(in_array($match, $optional_matches[2])) {
      unset($matches[0][$key]);
    }    
  }

  $sum = 0;

  // any shot names?
  if($matches[0]) {
    foreach($matches[0] as $match) {
      $sparqlparts = wisski_pathbuilder_get_sparql(substr($match, 1), $sparqlcondition, TRUE);        
      break;
    }
    
    $countsq = ("SELECT DISTINCT (count(?x" . (floor(count($samepart)/2)) . ") as ?num) WHERE { ");

    $sparql = ("SELECT ?x" . (floor(count($samepart)/2)) . " WHERE { ");
  
    foreach($sparqlparts["triples"] as $triple) {
      $sparql .= $triple . " . ";
      $countsq .= $triple . " . ";
    }

    $countsq .= $sparqlparts["end"];
    $sparql .= $sparqlparts["end"];
    
    if(variable_get("wisski_navigator_alphanumeric_sort", 1))
      $sparql .= (" ORDER BY xsd:integer(?out) LIMIT " . $limit . " OFFSET " . ($page * $limit));  
    else
      $sparql .= (" ORDER BY ?out LIMIT " . $limit . " OFFSET " . ($page * $limit));

    $sum = wisski_store_getObj()->wisski_ARCAdapter_getStore()->query($countsq);
    $sum = $sum['result']['rows'][0]['num'];
    $out = wisski_store_getObj()->wisski_ARCAdapter_getStore()->query($sparql);

  } else {
    $sparql = ("SELECT (COUNT(?x) AS ?z) WHERE { ?x <" . wisski_store_getObj()->wisski_ARCAdapter_delNamespace("rdf:type") . "> <" . $samepart["x" . (floor(count($samepart)/2))] . "> }");   

    $out = wisski_store_getObj()->wisski_ARCAdapter_getStore()->query($sparql);

    $sum = $out['result']['rows'][0]['z'];

    $sparql = ("SELECT ?x" . (floor(count($samepart)/2)) . " WHERE { ?x" . (floor(count($samepart)/2)) . " <" . wisski_store_getObj()->wisski_ARCAdapter_delNamespace("rdf:type") . "> <" . $samepart["x" . (floor(count($samepart)/2))] . "> }");
    $sparql .= (" ORDER BY ?x" . (floor(count($samepart)/2)) . " LIMIT " . $limit . " OFFSET " . ($page * $limit));

    $out = wisski_store_getObj()->wisski_ARCAdapter_getStore()->query($sparql);

  }

  
  $results = $out['result']['rows'];

  $pager_total_items[$element] = $sum;

  $pager_total[$element] = ceil($pager_total_items[$element] / $limit);
  $pager_page_array[$element] = max(0, min((int)
  $pager_page_array[$element], ((int) $pager_total[$element]) - 1));

  $prefix = "";
    
  $begin = ($page * $limit) + 1;
  $end = $begin - 1 + count($results) ;
  
  // get the correct style. This is used below.
  $style = variable_get('wisski_navigator_styleResultPage', 'list');
  // images? suppose yes!
  $image_support = variable_get('wisski_navigator_imageSupport', 'yes');
  
  //$prefix = '<div id="wki-navi-count"> Treffer ' . $begin . ' - ' . $end . ' von insgesamt ' . $sum . '</div>';
  // formulate a nice headline
  $form['heading'] = array(
    '#prefix' => '<label>',
    '#suffix' => '</label>',
    '#value' => t("Hits") . " " . $begin . " - " . min($end,$sum) . " " . t("of") . " " . $sum . ":",
  );

    $list = array();
    foreach($results as $result) {
        $uri = $result["x". (floor(count($samepart)/2))];
        $name = wisski_pathbuilder_generateGroupName(wisski_store_getObj()->wisski_ARCAdapter_addNamespace($uri), $groupdata['id'], $groupdata);
        if($image_support && $image_support == "yes") {
            $imgs = wisski_pathbuilder_getImages(wisski_store_getObj()->wisski_ARCAdapter_addNamespace($uri), 1);
            preg_match('/<img src="(.*?)"/', $imgs, $matches);
            if(!empty($matches[1])) {
                $value = "<div class='wisski_tileimg'><a href='".$uri."'><img src='".$matches[1]."'/></a></div><a href='".$uri."'>".$name."</a>";
            } else {
                $nopic = path_to_theme() . '/pics/img_nopic.png';
                global $base_url;
                if(is_file($nopic)) {
                    $value = "<div class='wisski_tileimg'><a href='".$uri."'><img src='".$base_url."/".$nopic."'/></a></div><a href='".$uri."'>".$name."</a>";
                } else {
                    $value = "<a href='".$uri."'>".$name."</a>";
                }    
            }
        } else {
            $value = "<a href='".$uri."'>".$name."</a>";
        }
        //$list[] = l($name, $result["x". (floor(count($samepart)/2))], array('html' => 'true'));
        $list[] = array('data' => $value, 'class'=> 'wisski_resultitem');
    }

    return drupal_render($form['heading']) . theme('item_list', $list, NULL, 'ul', array('class' => ($style == 'list' ? "wisski_resultlist" : "wisski_resulttiles"))) . theme('pager', NULL, 10, 0);
}

function wisski_navigator_overview($form_state = NULL) {
  $list = wisski_navigator_add_groups();

  $form['description'] = array(
    '#type' => 'markup',
    '#prefix' => '<p>',
    '#suffix' => '</p>',
     '#value' => t('Navigate the content'),
       '#weight' => 0,
  );
              
  return drupal_render($form) . theme('item_list', $list);
}

function wisski_navigator_enable() {
  wisski_navigator_add_groups();
}

function wisski_navigator_add_groups() {
  include_once(drupal_get_path('module', 'wisski_pathbuilder') . '/wisski_pathbuilder.inc');
  $myIDs = variable_get('wisski_navigator_menus', array());

  $groups = wisski_pathbuilder_getGroups();

  $saveIDs = array();
  
  foreach($myIDs as $id => $itemid) {
    $oldlinks[$itemid] = menu_link_load($id);
    if(!in_array($itemid, $groups))
      menu_link_delete($id);
  }
  
  $ret = array();
  
  foreach($groups as $group) {
    $data = wisski_pathbuilder_getPathData($group);
    if(!($data['enabled']))
      continue;
    $item = array();

    $item['link_path'] = ("navigate/" . $group);
    $item['link_title'] = $data['name'];

    $item['menu_name'] = isset($oldlinks[$group]['menu_name']) ? $oldlinks[$group]['menu_name']: "navigation";
    $item['weight'] = isset($oldlinks[$group]['weight']) ? $oldlinks[$group]['weight'] : 0;
    $item['expanded'] = isset($oldlinks[$group]['expanded']) ? $oldlinks[$group]['expanded'] : 0;
    $item['options'] = array();
    $item['mlid'] = isset($oldlinks[$group]['mlid']) ? $oldlinks[$group]['mlid'] : NULL;
    $item['hidden'] = isset($oldlinks[$group]['hidden']) ? $oldlinks[$group]['hidden'] : 0;
    $item['plid'] = isset($oldlinks[$group]['plid']) ? $oldlinks[$group]['plid'] : NULL;
      
    $id = menu_link_save(&$item);
    
    $saveIDs[$id] = $group;
    if($item['hidden'] == 0) { 
      if(module_exists("menu_per_role")) {
      	if(is_null(_menu_per_role_access($id))) {
          $string = '<dt>' . l($data['name'], ("navigate/" . $group)) . '</dt>';
          if(!empty($data['description']))
            $string .= '<dd>' . $data['description'] . '</dd>';
          if(!empty($item['weight']))
            $ret[$item['weight']] = $string;
          else
            $ret[] = $string;
        }
      }
      else {
        $string = '<dt>' . l($data['name'], ("navigate/" . $group)) . '</dt>';
        if(!empty($data['description']))
          $string .= '<dd>' . $data['description'] . '</dd>';
        if(!empty($item['weight']))
          $ret[$item['weight']] = $string;
        else
          $ret[] = $string;
      }
    }
  }

  ksort($ret);

  variable_set('wisski_navigator_menus', $saveIDs);

  return $ret;
  

}
